### ISSUE TITLE
using Gtk Failed 

### ISSUE THREAD

**Issue by liushang0322** [JuliaGraphics/Gtk.jl#596] opened 2021-11-22 01:56 UTC
julia> using Gtk
[ Info: Precompiling Gtk [4c0ca9eb-093a-5379-98c5-f87ac0bbbf44]
ERROR: LoadError: LoadError: InitError: could not load library "D:\TongYuan\.julia\artifacts\e5872943f1078a6397a4f4d0f760db959ec50630\bin\libffi-6.dll"
The specified module could not be found.

...

during initialization of module Libffi_jll
in expression starting at D:\TongYuan\.julia\packages\GTK3_jll\ebBBZ\src\wrappers\x86_64-w64-mingw32.jl:4
in expression starting at D:\TongYuan\.julia\packages\GTK3_jll\ebBBZ\src\GTK3_jll.jl:2  

...

Failed to precompile Gtk [4c0ca9eb-093a-5379-98c5-f87ac0bbbf44] to D:\TongYuan\.julia\compiled\v1.6\Gtk\jl_B81A.tmp.

**Comment by JeffFessler** [comment] 2021-11-28 02:09
It might help to report what version of Julia you are using and what version of Gtk.jl and exactly what OS (presumably some version of Windows from the paths shown).

**Comment by Leticia-maria** [comment] 2022-01-21 16:52
Hey, @JeffFessler I had the same problem of @liushang0322. I'm using Ubuntu 20.04 and Julia 1.7.1

**Comment by JeffFessler** [comment] 2022-01-21 22:20
I am not really a contributor here (I just updated some documentation once).   I did try to reproduce this issue, but it worked fine for me using ubuntu 18.04.6 and julia 1.7.1.  Sorry that I don't know what else to suggest and I hope your additional details will help the real maintainers.

**Comment by Leticia-maria** [comment] 2022-01-22 09:35
> I am not really a contributor here (I just updated some documentation once).   I did try to reproduce this issue, but it worked fine for me using ubuntu 18.04.6 and julia 1.7.1.  Sorry that I don't know what else to suggest and I hope your additional details will help the real maintainers.

I've solved on my machine

**Comment by lobingera** [comment] 2022-01-22 10:02
"I've solved on my machine" - Nice, but it would be helpful, if you explain, how.

**Comment by Leticia-maria** [comment] 2022-01-22 10:13
> "I've solved on my machine" - Nice, but it would be helpful, if you explain, how.

Clear the precompiled cache worked for me. Maybe one package that is not updated for the 1.7.1 version of Julia was blocking Gtk.

For example, you can try this command

```julia
map(rm,Base.find_all_in_cache_path(:BenchmarkTools))
```

Or

```bash
rm -rf ~/.julia/compiled
```

Please let me know if it was useful for you

**Comment by JeffFessler** [comment] 2022-01-22 13:41
Great!  Probably can close this issue then.

**Comment by tknopp** [comment] 2022-01-22 15:02
Closing this since it seems to be some precompilation hiccups.

**Closed by tknopp** 2022-01-22 15:02 UTC
