### ISSUE TITLE
Blank minimize/maximize buttons on Windows 7 with Julia 0.6.3

### ISSUE THREAD

**Issue by pauljurczak** [JuliaGraphics/Gtk.jl#355] opened 2018-06-15 04:14 UTC
Here is how the window with default parameters looks like:

![image](https://user-images.githubusercontent.com/4933032/41449773-4a956f22-7020-11e8-83e2-722edf8b69e7.png)

**Comment by tknopp** [comment] 2018-06-15 05:50
Then something happened to WinRPM and it packages. Here are the interesting lines:
https://github.com/JuliaGraphics/Gtk.jl/blob/master/deps/build.jl#L30

**Comment by pauljurczak** [comment] 2018-06-15 06:43
It's plausible, as I vaguely remember some warnings related to WinRPM build. I will try on another PC.

**Comment by pauljurczak** [comment] 2018-06-15 07:02
I have the same problem on Windows 10 PC. I have these packages installed:
7 required packages:
 - Compose                       0.6.0
 - GLVisualize                   0.7.0
 - Gtk                           0.14.0
 - IJulia                        1.8.0
 - ImageMagick                   0.5.1
 - ImageView                     0.6.0
 - OpenCL                        0.7.0

**Comment by tknopp** [comment] 2018-06-15 14:21
I would suggest running all `WinRPM` commands manually and trying to see where an error occurred. This includes the "schema" command and the end of the code that I quoted.

**Comment by mwawra** [comment] 2018-06-18 15:33
I just want to note, that the issue, I think, was already present with Julia v0.6.2.

To reproduce the problem one can also just load the gtk3-icon-browser from C:\Users\<username>\.julia\v0.6\WinRPM\deps\usr\x86_64-w64-mingw32\sys-root\mingw\bin. There you can also see that the symbolic-icons didn't work. I already installed gdk-pixbuf-loader-rsvg for svg-files but this didn't solved the problem. I think it really is a problem with the WinRPM-packages.

**Comment by w1res** [comment] 2018-10-23 19:06
I'm still getting this on julia 1.0.1 on Windows 10.

**Comment by pauljurczak** [comment] 2018-10-24 05:55
I'm also experiencing this behavior with a fresh install of Julia 1.0.1 on Windows 10.

**Comment by pauljurczak** [comment] 2018-11-10 04:50
Here is the solution I found: set environment variable `GTK_CSD=0` to enable Windows native decorations. It works fine with Windows 7 and 10. Thank you, stackoverflow!

**Comment by tknopp** [comment] 2018-11-10 07:34
Cool. Could you check if is possible to set that environment variable from within Julia? Then it could be set on Windows during initialization from Gtk.jl

**Comment by pauljurczak** [comment] 2018-11-10 08:07
@tknopp I think it should be set during the installation, but I'm a complete noob with Julia, so it's better done by whoever maintains the installer.

**Comment by Kelvyn88** [comment] 2020-07-17 00:20
Too late but, this works for me under Win and Linux. 

ENV["GTK_CSD"] = 0

Just copy and paste at the beginning of the code.

**Comment by tknopp** [comment] 2020-07-17 06:52
is that still an issue for current Gtk releases on Julia >= 1.3?

**Comment by Kelvyn88** [comment] 2020-07-17 07:02
Under Windows it is still needed to set the environment to allow windows decorations.

The above is the solution that I use in my projects. Could you close the Issue please? It was still open.

**Closed** 2020-07-17 07:52 UTC

**Comment by tknopp** [comment] 2020-07-17 07:54
@Kelvyn88  could you test master now? I have integrated your line into the init function of Gtk.jl

**Comment by Kelvyn88** [comment] 2020-07-17 08:01
@tknopp It works!! Thanks!
